### ISSUE TITLE
Auth check over-eager

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-grafana-datasource#36]
The auth check from #32 is over eager in the sense that it only works for Hawkular-Metrics, but not for Hawkular-services:

```
$ curl  -u jdoe:password http://localhost:8080/hawkular/metrics/tenants -HHawkular-Tenant:Hawkular
{"errorMsg":"Admin token is wrong or not specified."}
```

I found that just accessing / may be enough already:

```
$ curl  -u jdoe:password http://localhost:8080/hawkular/metrics/ -HHawkular-Tenant:Hawkular
{"Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f","name":"Hawkular-Metrics"}

```
vs

```
$ curl   http://localhost:8080/hawkular/metrics/ -HHawkular-Tenant:Hawkular
<html><head><title>Error</title></head><body>Unauthorized</body></html>
```

(of course the check for a valid tenant needs to be adjusted)

**Comment by jotak** [comment]
I checked the "/" endpoint with openshift and a bearer token, unfortunately it is allowed publicly without authentication. The bearer token can be wrong but the requests gives a correct response.

So I suggest to use another endpoint like 'http://localhost:8080/hawkular/metrics/metrics' to be sure that the authentication is checked
