### ISSUE TITLE
Docker image doesn't work in OCP

### ISSUE THREAD

**Issue by garethahealy** [hawkular/hawkular-grafana-datasource#40]
Due to the grafana base image using "gosu" - runs as root and switches to grafana, which in OCP isn't the user thats actually running the pod - and volumes for etc/grafana/plugins; it doesn't work in OCP out of the box and requires some fiddling.

Might be a good idea to just provide hawkulars own grafana docker image, instead of using upstreams. Had to do the following for a customer: https://github.com/garethahealy/grafana-docker/blob/master/Dockerfile

**Comment by jotak** [comment]
I also had some trouble with the official grafana image because it declares plugins location as a volume. I agree with providing our own grafana image.
