### ISSUE TITLE
Search by tags

### ISSUE THREAD

**Issue by agent462** [hawkular/hawkular-grafana-datasource#42]
I hope I'm doing something dumb but I've been unable to get the Search by tags working as an option.  I only ever get "select metric" option when building metrics for a panel.

I feel like I've tried everything.  I've followed:
http://www.hawkular.org/hawkular-clients/grafana/docs/quickstart-guide/
and
http://www.hawkular.org/blog/2016/10/24/hawkular-metrics-openshift-and-grafana.html

I've tried Grafana 4 and 3.1.  I've tried different versions of hawkular-grafana-datasource. I've tried your prebuilt container: https://hub.docker.com/r/hawkular/hawkular-grafana-datasource/

I'm using the OpenShift Hawkular.  When I create the templates/variables it pulls tags and I can see them at the bottom of the page.
![grafana](https://cloud.githubusercontent.com/assets/242283/21036465/9f1512ee-bd8b-11e6-817a-aecb082a00b0.PNG)

When adding a metric to the page; no luck with any "search by" options.
![grafana2](https://cloud.githubusercontent.com/assets/242283/21036508/dfa108c2-bd8b-11e6-8ca0-46464aa5a39e.PNG)

Any sanity help on what I'm missing?

**Comment by jotak** [comment]
Hi,
Can you check your version of hawkular metrics? You can get it from the url _[metrics server]/hawkular/metrics/status_

Querying by tag is only possible for metrics version >=0.20.0

**Comment by jotak** [comment]
(btw, I will update the documentation to mention that)

**Comment by jotak** [comment]
Note that if your version of hawkular-metrics is lower than 0.20.0 (but greater than 0.16.0), you can get a similar result than explain on the blog post ( http://www.hawkular.org/blog/2016/10/24/hawkular-metrics-openshift-and-grafana.html )

To do so, when you create a template variable just use the syntax to query metric ids, although it is more cumbersome, with "tags=" instead of "tags/": `tags=container_name:*`. That will give you results like `aloha/123-456-789/memory/usage`. You can use the Grafana regex field to extract the interesting parts. For example:

* Create variable "app" with query `tags=container_name:*` and regex `/([^\/]*)\/.*/`
* Create variable "pod_id" with query `tags=pod_id:*` and regex `/[^\/]*\/([^\/]*)/`

In dashboards, enter metric ids like: `$app/$pod_id/memory/usage`
And select whatever variable you want active in the top dropdown lists.

**Comment by agent462** [comment]
That's it -> 0.18.4.Final-redhat-1

What's sad is that's what RedHat is shipping with OpenShift.  We will need to update.

Thank you much!

**Comment by fche** [comment]
@jotak, I was not able to get your special template recipe working against a 0.18.5 hawkular (OS 3.3) instance.  Do you have by any chance a full grafana .json dashboard that demonstrates it?

**Comment by jotak** [comment]
@fche Unfortunately I don't have a dashboard for real openshift w/ hawkular 0.18.x but here's a example that I think should work:
 https://gist.github.com/jotak/55c1cfb19f1a5a80ac0d3d73d5fda541 . It's a dashboard with just a variable defined, nothing more.

Please tell me if it doesn't. On my side I've just emulated some metrics named for instance "aloha/123-456-789/memory/usage" or "hola/654-987-321/cpu/usage" and with tags "container_name", "pod_id" and "descriptor_name". As far as I know it should match with OS 3.3 metric names & tags. If not, then maybe you just have to adapt the regex. At least, you should see the full metric names when you write `tags=container_name:*` in Query without any regexp, can you confirm that?

**Comment by fche** [comment]
Thanks, progress. It seems that loading that dashboard was acceptable to hawkular, but apparently triggered an OOM-based crash/restart of the underlying cassandra instance.  The latter is being restricted to 2GB RAM.  Should that have been enough to answer basic queries like that one, when running against a realistic sized openshift cluster?

**Comment by jotak** [comment]
Hi, we would need just a clarification, to be sure if the OOM happens while querying "/metrics?tags=container_name:*" : you had this crash just while loading the provided dashboard, right? Without even starting to modify it, creating charts, etc?

**Comment by fche** [comment]
I'm not sure when exactly the crash happened.  From the grafana user's point of view, there are gateway timeouts or empty results or whatever.  The OOM messages were found in cluster admin logs (not available to me) reported around the same time.
