### ISSUE TITLE
Alerting Support for hawkular datasource

### ISSUE THREAD

**Issue by hardbone12** [hawkular/hawkular-grafana-datasource#47]
Im using grafana v4.1.0-beta1 (commit: v4.1.0-beta1) working with hawkular datasource plugin v1.0.6
the metrics works fine ,;)  But here is some alert config error:

tsdb.HandleRequest() error Could not find executor for data source type: hawkular-datasource

Does this mean that the hawkular datasource not support the alert function or i missed something?

![hawkular-alert](https://cloud.githubusercontent.com/assets/16435298/21514349/2856f798-ccff-11e6-83ab-d228031bc90d.png)

**Comment by jotak** [comment]
As far as I know it is not yet possible to support Grafana alerts within 3rd party plugins.
According to this issue (https://github.com/grafana/grafana/issues/5858 ) even built-in datasources are not all supported yet.

**Comment by pilhuhn** [comment]
I have hacked https://github.com/grafana/grafana/compare/master...pilhuhn:hawkular-alerts which allows you to set up alerting here (the warning would still show, as the plugin also needs a `alerts:true` element. Alerting would be done in/with Grafana and not hawkular-alerts though.

**Comment by rathna023023** [comment]
I need alerting to work for sqldb datasource, what will be the best idea

**Comment by cdan** [comment]
It seems grafana alert supports Prometheus now. Will hawkular add this feature in the near future?

**Comment by jotak** [comment]
Hi @cdan 
I don't think the situation has changed for us, Prometheus support for Grafana alerts doesn't go through the Prometheus datasource plugin, but through specific server-side code as we can see there: https://github.com/grafana/grafana/blob/7d205ae2b83fb35833dd902f8eb85cb53f631d32/pkg/tsdb/prometheus/prometheus.go

**Comment by kkraemer42** [comment]
Many thanks to @pilhuhn , just used your hack and it works after a slight codechange for the latest grafana version. Only question remaining for me: How do I disable strict certificate checking? 
Right now I get an error reading "x509: certificate signed by unknown authority". 
This is only an issue in alerting, the dashboard works fine and i get an alert, but inside the alert is only this error.

Would be very grateful for an answer.

**Comment by ttindell2** [comment]
So will this be ported into the actual official release? Not having alerts for Hawkular is not cool.

**Comment by jotak** [comment]
@ttindell2 that would need to be ported in core Grafana, and I doubt it can happen :(
But Hawkular has its own alerting component that's worth seeing: http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html

**Comment by hardbone12** [comment]
Migrated to the [openshift/cluster-monitoring-operator](https://github.com/openshift/cluster-monitoring-operator) project, So close this issue.
