### ISSUE TITLE
Openshift Persistent template service selector does not match with pod

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [hawkular/hawkular-grafana-datasource#48]
Hi.

I am using https://github.com/hawkular/hawkular-grafana-datasource/blob/master/docker/openshift/openshift-template-persistent.yml for deploying the hawkular-grafana in Openshift Origin 1.4.0-rc1.

The service selector does not match with pod. The fix consists on deleting the "deploymentconfig" label in the selector match.

However, it has to be confirmed that works also in OCP 3.3.

**Comment by gordillo-ramon-redhat** [comment]
In OCP 3.3, the template works "as is". Good to test with OCP 3.4 after release.

**Comment by garethahealy** [comment]
@gordillo-ramon-redhat can you retest with the following template?

`oc process -f https://raw.githubusercontent.com/garethahealy/hawkular-grafana-datasource/master/docker/openshift/openshift-template-ephemeral.yaml | oc create -f -`

https://github.com/garethahealy/hawkular-grafana-datasource/commit/87977a345789a59aa759759986a68dc951014e9f

Have tested locally on minishift v1.4.0-rc1 and works.

**Comment by garethahealy** [comment]
@gordillo-ramon-redhat have you had chance to check with the updated template?

**Comment by gordillo-ramon-redhat** [comment]
It is strange. The behaviour is exactly the same as in the original, if you go to the console, it show you the route and the service, an it says they are not attached to a dc or pod, but...

When you use the route, it redirects to the app. It makes me wonder if the problem is in the console and not in the route/service/dc.

Though, I guess it is a bug in Openshift rather than in the template. Anyway, if you delete the "deploymentconfig" from the service selector, the console finds everything ok.

You can close this issue IMHO.
