### ISSUE TITLE
Customize legend

### ISSUE THREAD

**Issue by jotak** [hawkular/hawkular-grafana-datasource#58]
Provide a way to display custom legend instead of the metric name, which sometimes is not user-friendly at all.

Allow the use of variables / tags in legend template?

**Comment by hardbone12** [comment]
Maybe just use "pod_name", "pod_namespace/pod_name" or other tag value will be better

**Comment by jotak** [comment]
Yes, that would be nice, the only thing that is bugging me is that the current REST API doesn't return tags with metric data, which means that for each query I would have to perform a second http request to get the tag values of the returned metrics.

Or change the REST API.

**Comment by hardbone12** [comment]
Agree, Without change the REST API may need to implement mapping tags API response data to raw/query 
 API data.

**Comment by pat2man** [comment]
What about some sort of regex?

For instance, with OpenShift router metrics and hawkular-openshift-agent I get the following metric:

```pod/c6e2a9ab-8d1c-11e7-b7be-06415eb17bbf/custom/haproxy_server_bytes_in_total{namespace=my-namespace,pod=web-45-6f464,route=web,server=10.1.10.138:8080,service=web}```

I have the pod name there in the name, but it gets cut off in the legend because it is too long. Regex could be static and still give me the pod name.

**Comment by LarsMilland** [comment]
Would any solution on this issue reach a conclusion in the near future. We would also like to have such a feature with either regex or through use of other tags from the metrics to populate the legend descriptive values. We are using the Hawkular Datasource plugin with metrics collected from OpenShift so have also long and non-usable metric names.

**Comment by jotak** [comment]
> For instance, with OpenShift router metrics and hawkular-openshift-agent I get the following metric:

> pod/c6e2a9ab-8d1c-11e7-b7be-06415eb17bbf/custom/haproxy_server_bytes_in_total{namespace=my-namespace,pod=web-45-6f464,route=web,server=10.1.10.138:8080,service=web}

Wow, it must have changed since the last time I used it. It looks like a prometheus metric name, now. There's definitely some regexp that could be done here. I will have a look when I have some time for it, but in the meantime don't forget that PRs are welcome :-)

**Comment by jotak** [comment]
Ok just figured out it's HOSA naming. I'm not so much familiar with it, but any solution would have to be generic enough, not just focused on HOSA.

So, I can imagine a "legend" text field where one would type for instance:
`HAProxy Server Bytes {{namespace=([^,}]+)}} / {{pod=([^,}]+)}}`

which would result in:
`HAProxy Server Bytes my-namespace / web-45-6f464`
based on the original name
`pod/c6e2a9ab-8d1c-11e7-b7be-06415eb17bbf/custom/haproxy_server_bytes_in_total{namespace=my-namespace,pod=web-45-6f464,route=web,server=10.1.10.138:8080,service=web}`

What do you think?

**Comment by jotak** [comment]
If anyone wants to use before it's released, there's a docker image available with the PR: `hawkular/hawkular-grafana-datasource:dev-build` (docker hub)

**Comment by jotak** [comment]
released in 1.1.2
