### ISSUE TITLE
Cant Add Hawkular Dashboard 

### ISSUE THREAD

**Issue by novonilc** [hawkular/hawkular-grafana-datasource#67]
I cant add hawkular dashboard from https://github.com/hawkular/hawkular-grafana-datasource/blob/master/dashboards/openshift-memory-example.json . It gives error 'cant find hawkular datastore' . hawkular datastore is successfully deployed though 
![image](https://cloud.githubusercontent.com/assets/15949053/25297996/5696beda-26a6-11e7-8fe5-5bbc5b9a509f.png)

**Comment by jotak** [comment]
Hey,
You're right, this dashboard has been broken when the plugin id was changed some time ago.
I've sent a pull request, but you can manually edit the dashboard's json to replace the plugin id "hawkular" with "hawkular-datasource", then try again.
See the changes here: https://github.com/hawkular/hawkular-grafana-datasource/pull/68/files
