### ISSUE TITLE
Edit Graph "Metrics Query" can not Toggle Edit Mode

### ISSUE THREAD

**Issue by hardbone12** [hawkular/hawkular-grafana-datasource#86]
I used some Templating to filter metric tags. When the metric tags variable has contains "."  Can not be returned from edit mode. And browser console has some errors 

Query expression:
nodename IN [$node] AND descriptor_name IN [$metrics] AND type IN [$type] AND labels.application IN [$app] AND labels.application_model IN [$app_model]

![image](https://user-images.githubusercontent.com/16435298/29766913-0504c6d4-8c13-11e7-94c3-a99c4e3843c9.png)

Enviroments:

Grafana v4.4.2 (commit: 6d9cbdd)

package.json :
{
  "name": "hawkular-grafana-datasource",
  "version": "1.0.10",
  "description": "Hawkular Datasource for Grafana",
  "homepage": "https://github.com/hawkular/hawkular-grafana-datasource",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/hawkular/hawkular-grafana-datasource.git"
  },
  "author": "Red Hat",
  "license": "Apache-2.0",
  "devDependencies": {
    "babel": "^6.23.0",
    "chai": "~3.5.0",
    "grunt": "^1.0.1",
    "grunt-babel": "~6.0.0",
    "grunt-bump": "0.8.0",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-clean": "^1.1.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-uglify": "^2.3.0",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-execute": "~0.2.2",
    "grunt-mocha-test": "^0.13.2",
    "grunt-systemjs-builder": "^1.0.0",
    "jsdom": "~9.12.0",
    "load-grunt-tasks": "^3.5.2",
    "prunk": "^1.3.0",
    "q": "^1.5.0"
  },
  "dependencies": {
    "babel-plugin-transform-es2015-for-of": "^6.6.0",
    "babel-plugin-transform-es2015-modules-systemjs": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "lodash": "^4.17.4",
    "mocha": "^3.2.0"
  },
  "scripts": {
    "test": "grunt"
  }
}

**Comment by jotak** [comment]
It seems that a server-side change got unnoticed here ( related to https://issues.jboss.org/browse/HWKMETRICS-611 ). Dot is going to be added as allowed character for tag names.

**Comment by hardbone12** [comment]
Define a pod_label_tags-prefix global setting on hawkular-openshift-agent configMap can also solve this ;)
collector:
  pod_label_tags_prefix: labels_

Thanks. I rebuild the plugin. It works for me.
