### ISSUE TITLE
[Tenant per query]

### ISSUE THREAD

**Issue by xhottam** [hawkular/hawkular-grafana-datasource#94]
"hawkular-grafana-datasource", "version": "1.1.0"

I'm unable to  variabilize "Tenant" field in "Metrics" from one "Templating-Variables." If is it possible?

as example:
name : 
values: skydive,infrastructure

[OK]query with Tenant hand-populated as "infrastructure"
Request heaader : Hawkular-Tenant infrastructure
{"start":1507910103999,"end":1507910404002,"order":"ASC","tags":"container_name:*,descriptor_name:memory/request"}

[KO]query with Tenant variable-populated as  $tenant as "infrastructure"

Request heaader : Hawkular-Tenant $tenant
{"start":1507910662812,"end":1507910962813,"order":"ASC","tags":"container_name:*,descriptor_name:memory/request"}

Also, is any way to ask hawkular through  "hawkular-grafana-datasource" and give al the tenants of the cluster?

**Comment by jotak** [comment]
Hi @xhottam , do you have the ability to test with PR #93 , if you have access to your grafana deployment? It should fix this issue.
If you need a docker image, I've built one out of this PR: hawkular/hawkular-grafana-datasource:pr-93  (available on dockerhub)

**Comment by sbadakhc** [comment]
Hi,

I'm also interested in being able to monitor all the the projects on my openshift without having to set up a datasource for each tenant. Is this possible?

**Comment by jotak** [comment]
@sbadakhc yes, it's the purpose of the recent PRs #91 (merged) and #93 (not merged yet, fixing bug in the former).
As per my previous comment, feel free to try a provide feedback. I'd be really glad if it could be validated against openshift use cases before we release.

**Comment by sbadakhc** [comment]
I'm happy to test and feedback. Thanks.

**Comment by steveteuber** [comment]
@jotak Docker Image `hawkular/hawkular-grafana-datasource:pr-93` it is working just fine!

**Comment by ljuaneda** [comment]
+1
Tests ok too with grafana 4.6.1

**Comment by jotak** [comment]
@steveteuber @ljuaneda thanks for your feedback, I'm proceeding to the release & docker image push

**Comment by jotak** [comment]
Just released 1.1.1 with the fix. The dockerhub registry has been updated too.
