### ISSUE TITLE
Duplicate names with multiple series aggregation

### ISSUE THREAD

**Issue by ctron** [hawkular/hawkular-grafana-datasource#99]
Using the feature "Multiple series aggregation" might create duplicate names when using it more than once in a graph.

Steps to reproduce:
* Add two metrics
* Aggregate both with (e.g.) Sum -> Stat type "sum"

Result:
* You have two metrics named "sum" and no way to change them

Expected Result:
* As metrics are actually named "A", "B" it could use those to avoid collision.
* Or simply allow to put in an alias

**Comment by jotak** [comment]
There is a new field "legend" that is exactly for this purpose (see #58 ) , but I 've just checked with multiple series aggregation it is not used to override the series name as expected. 
I'm working on a fix.

**Comment by jotak** [comment]
It's merged, docker image : `hawkular/hawkular-grafana-datasource:dev-build` (docker hub)
We'll probably release beginning of next week if nothing else comes up..

**Comment by jbares83** [comment]
Any update regarding to the issue

**Comment by jotak** [comment]
@jbares83 it was available for a while if you build from source or if you use a docker image (I provided the name above: `hawkular/hawkular-grafana-datasource:dev-build` (docker hub)

I'm currently releasing and pushing 1.1.2 to dockerhub

**Comment by jotak** [comment]
Fixed in 1.1.2 https://github.com/hawkular/hawkular-grafana-datasource/releases/tag/v1.1.2
